version: 2

sources:
  - name: pentaho
    tables:
      - name: "HumanResources.Employee"
      - name: "Person.Person"
      - name: "Production.ProductCostHistory"
      - name: "Purchasing.PurchaseOrderDetail"
      - name: "Purchasing.PurchaseOrderHeader"
      - name: "Purchasing.Vendor"
      - name: "Sales.Customer"
      - name: "Sales.SalesOrderDetail"
      - name: "Sales.SalesOrderHeader"
      - name: "Sales.SalesPerson"
      - name: "Sales.SalesTerritory"
      - name: "Sales.Store"
      - name: "[Production].[ProductCategory]"
      - name: "[Production].[ProductModel]"
      - name: "[Production].[ProductSubcategory]"
      - name: "[Production].[Product]"
      - name: "dim_product"
      - name: "dim_sales_person"
      - name: "eae_data_management_mmjja.dim_sales_territory"
      - name: "fact_purchases"
      - name: "fact_sales"
      - name: "staging_data_management_mmjja.staging_date"
      - name: "staging_date"

models:
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_0_0
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_0_1
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_1_0
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_1_1
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_2_0
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_2_1
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_2_2
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_2_3
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_3_0
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_3_1
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_3_2
  - name: db_scripts_destination_mysql_datamart_testing_scenarios_sql_3_3
  - name: dim_customer_ktr_0
  - name: dim_customer_ktr_1
  - name: dim_customer_ktr_2
  - name: dim_customer_ktr_3
  - name: dim_customer_ktr_4
  - name: dim_customer_ktr_5
  - name: dim_customer_ktr_6
  - name: dim_customer_ktr_7
  - name: dim_customer_ktr_8
  - name: dim_customer_ktr_9
  - name: dim_date_ktr_0
  - name: dim_date_ktr_1
  - name: dim_date_ktr_10
  - name: dim_date_ktr_11
  - name: dim_date_ktr_12
  - name: dim_date_ktr_13
  - name: dim_date_ktr_2
  - name: dim_date_ktr_3
  - name: dim_date_ktr_4
  - name: dim_date_ktr_5
  - name: dim_date_ktr_6
  - name: dim_date_ktr_7
  - name: dim_date_ktr_8
  - name: dim_date_ktr_9
  - name: dim_product_ktr_0
  - name: dim_product_ktr_1
  - name: dim_product_ktr_2
  - name: dim_product_ktr_3
  - name: dim_product_ktr_4
  - name: dim_product_ktr_5
  - name: dim_product_ktr_6
  - name: dim_product_ktr_7
  - name: dim_product_ktr_8
  - name: dim_sales_person_ktr_0
  - name: dim_sales_person_ktr_1
  - name: dim_sales_person_ktr_2
  - name: dim_sales_person_ktr_3
  - name: dim_sales_person_ktr_4
  - name: dim_sales_person_ktr_5
  - name: dim_sales_person_ktr_6
  - name: dim_sales_person_ktr_7
  - name: dim_sales_territory_ktr_0
  - name: dim_sales_territory_ktr_1
  - name: dim_sales_territory_ktr_2
  - name: dim_vendor_ktr_0
  - name: dim_vendor_ktr_1
  - name: dim_vendor_ktr_2
  - name: dimensionsjob_kjb_0
  - name: dimensionsjob_kjb_1
  - name: dimensionsjob_kjb_2
  - name: dimensionsjob_kjb_3
  - name: dimensionsjob_kjb_4
  - name: dimensionsjob_kjb_5
  - name: dimensionsjob_kjb_6
  - name: dimensionsjob_kjb_7
  - name: fact_purchase_ktr_0
  - name: fact_purchase_ktr_1
  - name: fact_purchase_ktr_2
  - name: fact_purchase_ktr_3
  - name: fact_purchase_ktr_4
  - name: fact_purchase_ktr_5
  - name: fact_purchase_ktr_6
  - name: fact_purchase_ktr_7
  - name: fact_purchase_ktr_8
  - name: fact_sales_ktr_0
  - name: fact_sales_ktr_1
  - name: fact_sales_ktr_10
  - name: fact_sales_ktr_11
  - name: fact_sales_ktr_12
  - name: fact_sales_ktr_13
  - name: fact_sales_ktr_14
  - name: fact_sales_ktr_15
  - name: fact_sales_ktr_16
  - name: fact_sales_ktr_17
  - name: fact_sales_ktr_2
  - name: fact_sales_ktr_3
  - name: fact_sales_ktr_4
  - name: fact_sales_ktr_5
  - name: fact_sales_ktr_6
  - name: fact_sales_ktr_7
  - name: fact_sales_ktr_8
  - name: fact_sales_ktr_9
  - name: factsjob_kjb_0
  - name: factsjob_kjb_1
  - name: factsjob_kjb_2
  - name: factsjob_kjb_3
